In [ ]:
import pandas as pd
import numpy as np

In [ ]:
d = pd.read_csv('cars.csv')

In [ ]:
d.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
d['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [ ]:
d['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [ ]:
d['brand'].value_counts()        #each unique_variable frequency in the specified column

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
d['brand'].nunique()        #the total number of unique_variables in given column

32

ONEHOTENCODING USING PANDAS

In [ ]:
#not taking brand now only considering the fuel&owner(categorical) column as there are very unique variab under it so just this
#pd.get_dummies( d , columns = ['fuel' , 'owner' ] ) ,  converts the categorical_cols into one-hot_encoded_categ's

pd.get_dummies( d , columns = ['fuel' , 'owner' ])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

ONEHOTENCODING using (K-1) categories means drop the first column

In [ ]:
# will now drop the first column to avoid multicollinearity  so instead of nth col
# only n-1 cols will be taken so it means , that from each specifc col 1first willbedrop

pd.get_dummies( d , columns = ['fuel' , 'owner' ] , drop_first='True' )

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [ ]:
#   pandas - get_dummies() it  doesn't remember the categories , so not recommended for the ml projects
print(d.shape)
d.head()
# as you can see that it cannot remember , and its the same o/p

(8128, 5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

ONEHOTENCODING USING SCIKIT-LEARN

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split( d.iloc[ : , 0 : 4 ] , d.iloc[: , -1]  , random_state = 1 , test_size = 0.2)

In [ ]:
x_train.head()                # 80% of 8128

        brand  km_driven    fuel         owner
1939    Honda     100000  Diesel  Second Owner
5455   Maruti     120000  Diesel  Second Owner
7079  Renault     100000  Diesel  Second Owner
2000    Honda      80000  Petrol  Second Owner
1578    Honda      56494  Petrol   First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()      #by default produces a sparse matrix

# as sparse matrix is type of matrix where most valueare 0's only ,ex- if you have 1000 rows and 50 unique categories, your resulting matrix will be 1000×50, but each row will contain only one 1, and the rest will be 0.
# lot of waste space OneHotEncoder uses a sparse matrix by default to save memory and improve performance, especially when most values are zeros
# can change it to a normal (dense) array using sparse=False or .toarray()

In [ ]:
ohe.fit_transform(x_train[['fuel' , 'owner']] )       #9columns fuel-4 , owner-5

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 9)>

In [ ]:
ohe.fit_transform(x_train[['fuel' , 'owner']]).toarray()

array([[0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
x_train_new = ohe.fit_transform(x_train[['fuel' , 'owner']]).toarray()   # as fit is only applied to the train only as so that data will not be loose to the train set , which is good practise
# here it's combines the fit& transform otherwise u can seperate it
x_test_new = ohe.transform(x_test[['fuel' , 'owner']]).toarray()

In [ ]:
x_train_new             # numpy array

array([[0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
# also need to be added to the brand and km driven column
x_train[['brand', 'km_driven']]

        brand  km_driven
1939    Honda     100000
5455   Maruti     120000
7079  Renault     100000
2000    Honda      80000
1578    Honda      56494
...       ...        ...
7935   Maruti     100000
5192  Hyundai     152000
3980  Hyundai      70000
235    Maruti     110000
5157   Maruti      65755

[6502 rows x 2 columns]

In [ ]:
x_train[['brand', 'km_driven']].values                  # numpy array

array([['Honda', 100000],
       ['Maruti', 120000],
       ['Renault', 100000],
       ...,
       ['Hyundai', 70000],
       ['Maruti', 110000],
       ['Maruti', 65755]], dtype=object)

In [ ]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))
# np.hsatck( ) Horizontally stacks the original values (brand and km_driven) with the one-hot encoded values of fuel and owner
# This creates a new dataset that includes both the numerical and categorical features.

array([['Honda', 100000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 120000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Renault', 100000, 0.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Hyundai', 70000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 110000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Maruti', 65755, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [ ]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape      # u can see that the cols are get added

(6502, 11)

ONE HOTENCODING WITH TOP_CATEGORIES

In [ ]:
cnt = d.brand.value_counts()
cnt

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
# selecting the freq/threshold that under it the brands will come under it
threshold = 100

In [ ]:
replace_ = cnt[cnt <= threshold].index
replace_

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [ ]:
pd.get_dummies(d['brand'].replace(replace_ , 'uncommon')).sample(4)      #here uncommon is the word that means that the rare brand with (less_freq<100) is merge with the uncommone label
# so all shown above in o/p comes under it

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
1017,False,False,False,False,True,False,False,False,False,False,False,False,False
4294,False,False,False,False,True,False,False,False,False,False,False,False,False
5365,False,False,False,False,False,False,False,True,False,False,False,False,False
5168,False,False,True,False,False,False,False,False,False,False,False,False,False