In [1]:
import pandas as pd

In [2]:
time   = pd.read_csv('messages.csv')
dt= pd.read_csv('orders.csv')

In [3]:
dt

           date  product_id  city_id  orders
0    2019-12-10        5628       25       3
1    2018-08-15        3646       14     157
2    2018-10-23        1859       25       1
3    2019-08-17        7292       25       1
4    2019-01-06        4344       25       3
..          ...         ...      ...     ...
995  2018-10-08         255       13       1
996  2018-12-06        5521        7       1
997  2019-05-07         487       26      14
998  2019-03-03        1503       21       2
999  2019-10-15        6371        7      22

[1000 rows x 4 columns]

In [4]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [5]:
# date and time are in string format so we have to change its datatype object
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

WORKING WITH DATE

In [6]:
dt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
dt['date'] = pd.to_datetime(dt['date'])
dt.info()
# the object i.e string has been convertedto datetotime

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

EXTRACT Year/mon/day

In [8]:
dt['date_year'] = dt['date'].dt.year
dt['date_month'] = dt['date'].dt.month
dt['date_day']  = dt['date'].dt.day

dt['date_month_name'] = dt['date'].dt.month_name()
dt.sample(8)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
331,2019-10-21,6729,14,1,2019,10,21,October
151,2019-10-15,5066,18,14,2019,10,15,October
713,2018-10-14,4269,22,2,2018,10,14,October
911,2019-08-12,3315,14,3,2019,8,12,August
981,2019-06-17,7526,14,12,2019,6,17,June
538,2018-08-24,4885,16,25,2018,8,24,August
584,2018-12-16,1520,26,168,2018,12,16,December
262,2018-11-14,4667,9,1,2018,11,14,November

In [9]:
dt['date_week']  = dt['date'].dt.day_of_week
dt['date_day_name']=dt['date'].dt.day_name()
dt.sample(8)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_day_name
835,2019-04-27,2736,25,5,2019,4,27,April,5,Saturday
578,2019-06-28,5922,25,2,2019,6,28,June,4,Friday
653,2019-02-27,6937,13,14,2019,2,27,February,2,Wednesday
342,2019-07-31,4509,22,4,2019,7,31,July,2,Wednesday
816,2019-02-15,6634,25,5,2019,2,15,February,4,Friday
538,2018-08-24,4885,16,25,2018,8,24,August,4,Friday
253,2018-10-13,3793,22,32,2018,10,13,October,5,Saturday
270,2019-11-23,704,13,10,2019,11,23,November,5,Saturday

In [10]:
 # the particular was weekend or not
import numpy as np

dt['date_isweekend'] = dt['date_day_name'].isin(['Saturday', 'Sunday'])
dt = dt.drop(columns=['product_id','city_id','orders'])
dt.sample(8)

,date,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_isweekend
444,2019-07-24,2019,7,24,July,2,Wednesday,False
323,2018-11-19,2018,11,19,November,0,Monday,False
77,2018-11-02,2018,11,2,November,4,Friday,False
204,2018-10-07,2018,10,7,October,6,Sunday,True
841,2019-11-17,2019,11,17,November,6,Sunday,True
480,2019-02-06,2019,2,6,February,2,Wednesday,False
759,2019-11-23,2019,11,23,November,5,Saturday,True
412,2018-10-10,2018,10,10,October,2,Wednesday,False

In [11]:
# np.where asign values accroding to the condn;s
dt['date_isweekend'] = np.where(dt['date_day_name'].isin(['Saturday', 'Sunday']) ,1,0)
dt['date_week'] = dt['date'].dt.isocalendar().week
dt.sample(8)

,date,date_year,date_month,date_day,date_month_name,date_week,date_day_name,date_isweekend
875,2018-11-01,2018,11,1,November,44,Thursday,0
251,2018-11-14,2018,11,14,November,46,Wednesday,0
122,2019-12-04,2019,12,4,December,49,Wednesday,0
35,2019-01-20,2019,1,20,January,3,Sunday,1
183,2019-02-08,2019,2,8,February,6,Friday,0
378,2019-03-18,2019,3,18,March,12,Monday,0
134,2019-11-17,2019,11,17,November,46,Sunday,1
407,2019-07-23,2019,7,23,July,30,Tuesday,0

EXTRACT TIME ELAPSED BETWEEN DATES

In [12]:
# means the time diff between two dates
# showing the utc by default
import datetime
today= datetime.datetime.today()
today

datetime.datetime(2025, 7, 16, 17, 25, 15, 112007)

In [13]:
import pytz

ist = pytz.timezone('Asia/Kolkata')
now_ist = datetime.datetime.now(ist)
print(now_ist)

2025-07-16 22:55:15.175022+05:30

In [14]:
today - dt['date']
(today - dt['date']).dt.days

0      2045
1      2527
2      2458
3      2160
4      2383
       ...
995    2473
996    2414
997    2262
998    2327
999    2101
Name: date, Length: 1000, dtype: int64

WORKING WITH TIME

In [31]:
time = pd.read_csv('messages.csv')
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [33]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [42]:
time['sec'] = time['date'].dt.second
time['minute'] = time['date'].dt.minute
time['hour'] = time['date'].dt.hour
time['time'] = time['date'].dt.time
time.sample(5)

,date,msg,sec,minute,hour,time
752,2015-11-10 23:46:00,Олечка милая я тебя очень сильно люблю. Ты пре...,0,46,23,23:46:00
521,2014-05-20 23:34:00,Днепр Пар 30лет познак с Жен 40-50лет для встр...,0,34,23,23:34:00
60,2014-10-20 00:40:00,Для милой и нежной девушки 26.,0,40,0,00:40:00
111,2015-09-25 01:16:00,готов приехать в гости или вы девочки мне 24 х...,0,16,1,01:16:00
882,2012-03-31 00:28:00,ПАРЕНЬ ПРИГЛАСИТ СЕЙЧАС В ГОСТИ Д/Ж 0951596297,0,28,0,00:28:00

In [45]:
(today -time['date']).sample(8)

706   4879 days 17:30:15.112007
357   3702 days 16:02:15.112007
231   4431 days 15:25:15.112007
51    3559 days 16:28:15.112007
295   4576 days 15:40:15.112007
651   3482 days 16:41:15.112007
578   3819 days 15:53:15.112007
719   4684 days 16:19:15.112007
Name: date, dtype: timedelta64[ns]